name: Java Maven with Selenium Tests
'on':
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
        options: '--network-alias selenium -p 4444:4444'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: '${{ runner.os }}-maven-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install Maven dependencies
        run: mvn install -DskipTests
      - name: Run tests
        env:
          SELENIUM_URL: 'http://localhost:4444/wd/hub'
        run: mvn test
